[package]
name = "bevy-test-app"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "bevy_render",
    "bevy_core_pipeline", 
    "bevy_asset",
    "bevy_scene",
    "bevy_pbr",
    "png"
] }
