name: GPU Test

on: [push]

jobs:
  gpu:
    runs-on: lite-gpu-runner
    steps:
      - uses: actions/checkout@v3

      - name: Show GPU Info
        run: nvidia-smi

      - name: Install Rust and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Bevy test app
        run: |
          cd bevy-test-app
          cargo run --release
